input:
  bamdir: "./data/GOM"
  bed: "./data/GOM/GOM.bed"
  fasta: "./data/REF/hg19.fa"
  rbams: null

output:
  dir: "./result_GOMv2_standard"
  prefix: "GOM"

settings:
  modechrom: "A"
  min_corr: 0.98
  min_cov: 100
  min_total_reads: 300000
  max_exon_cv: 0.5
  transition_probability: 0.0001
  expected_CNV_length: 50000
  n_bins_reduced: 10000
  phi_bins: 1
  formula: "cbind(test, reference) ~ 1"
  score_high_corr: 0.985
  score_med_corr: 0.95
  score_high_refs: 3
  score_med_refs: 2
  score_low_ratio_low: 0.75
  score_low_ratio_high: 1.25
  score_high_ratio_low: 0.70
  score_high_ratio_high: 1.30
  score_med_ratio_low: 0.60
  score_med_ratio_high: 1.40
  score_low_confidence_genes: ["PMS2", "SMN1", "CYP2D6", "HBA1", "HBA2", "STRC", "CYP21A2", "GBA1", "CFTR"]

# -------------------------------
# BED PREPROCESSING
# -------------------------------
bed_preprocess:
  bed_process: "STANDARD"
  genome_version: "hg19"
  unknown_gene: false
  exon_sep: "_"                 # Split token used to break apart complex labels
  
  # Configuration for complex gene identifiers (when auto_exon_number is false)
  gene_name_keep: "2"         # Keeps parts 1 and 2 joined together (e.g., "MUC4_PROT")
  
  customexon: true
  bed_zero_based: true
  skip_invalid_intervals: true
  
  # Region Numbering Controls
  auto_exon_number: false       # Set to FALSE to switch from global genomic order re-numbering
  region_numbering_mode: "file_order" # "bed_text" to keep old text digits, or "file_order" for pure per-region sequential indexes